### ISSUE TITLE
categories can not be loaded. unexpected character 

### ISSUE THREAD

**Issue by Aaaamu** [Teifun2/nextcloud-cookbook-flutter#92] opened 2021-12-05 22:08 UTC
Description
when i open the app i see my receipies for a second then the error message in the screenshot appears and no functionality is left. Recinnecting to the account does not help.

Reproduction
i use the latest lineage os on a one+5 phone

Screenshots

![Screenshot_20211205-184501_Nextcloud_Cookbook](https://user-images.githubusercontent.com/23037248/144765796-aeecb667-0229-482a-834b-bd49a0a68aa9.png)

Versions

Cookbook 0.7.0
nextclod server v 21.0.2

**Comment by Teifun2** [comment] 2021-12-12 12:51
Hello @Aaaamu thanks for reporting this issue.

I'm currently not aware why this happens an I will try to reproduce it!

However if you want i can send you the "links" that the app fetches so we can figure out what exactly goes wrong!

**Comment by Teifun2** [comment] 2021-12-18 22:08
@Aaaamu Can you please open the following url in the browser while being logged into your nextcloud account?
YOUR-HOST/index.php/apps/cookbook/categories

this should show you a json formated string with all your categories.
Example:
[{"name":"Appetizer","recipe_count":"1"},{"name":"Dessert","recipe_count":"3"},{"name":"Dinner","recipe_count":"1"},{"name":"Soup","recipe_count":"2"},{"name":"*","recipe_count":"9"}]

Can you tell me what is shown for you?

**Comment by Aaaamu** [comment] 2021-12-23 20:22
it works again! I think your app did not update, but i updated nextcloud to Nextcloud 22.2.3

**Comment by Teifun2** [comment] 2021-12-25 15:16
@Aaaamu Greate to hear. It is weird that there seemed to be an issue but i will close this for know as it will be hard to figure out what was wrong before!

**Comment by dudeofawesome** [comment] 2022-01-04 03:01
I'm now having the same issue. If I hit the categories endpoint through my browser it sends the JSON payload just fine though.

**Comment by dudeofawesome** [comment] 2022-01-05 03:25
Hmm, looks like my issue was caused by a recipe having the `.` category accidentally. Probably more of an API issue than a client issue in that case.

**Comment by Teifun2** [comment] 2022-01-05 10:05
@dudeofawesome Oh thanks for this information.

I will check why / if this breaks my client but this is very helpful information!

**Comment by Teifun2** [comment] 2022-04-09 12:05
I thoroughly chekced the code.

It seems that some library is sanitazing the url
FROM:
host/index.php/apps/cookbook/api/category/.
TO: 
host/index.php/apps/cookbook/api/category/

Sadly i dont see a way to fix this. Except of corse to advise people to not add such a Category.

**Comment by Aaaamu** [comment] 2022-04-10 08:32
Luckily it is eaay to fix once you know the problem. Maybe a good candidate for an f.a.q question? Maybe these entries could also be avoided by a validity check in the editing form and in the import script?

Am 9. April 2022 14:05:28 MESZ schrieb Teifun2 ***@***.***>:
>I thoroughly chekced the code.
>
>It seems that some library is sanitazing the url
>FROM:
>host/index.php/apps/cookbook/api/category/.
>TO: 
>host/index.php/apps/cookbook/api/category/
>
>Sadly i dont see a way to fix this. Except of corse to advise people to not add such a Category.
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/Teifun2/nextcloud-cookbook-flutter/issues/92#issuecomment-1093963299
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Teifun2** [comment] 2022-04-10 21:27
` Maybe these entries could also be avoided by a validity check in the editing form and in the import script?`

As it is no longer crashing the category screen and only makes it so that the recipes and images of this category cannot be loaded i will not do this. It shoul be vairly easy to figure out for everyone why this category could lead to trouble,

This should be fixed with version 0.7.6

**Closed by Teifun2** 2022-04-10 21:27 UTC
Labels: bug, delivery
