### ISSUE TITLE
Blurred thumbnails on larger screens

### ISSUE THREAD

**Issue by GutHib** [Teifun2/nextcloud-cookbook-flutter#28] opened 2020-11-09 12:25 UTC
As it seems, the thumbnails used for the main screen categories aren't big enough to fit the purpose. On my phone, they look alright (although not super-sharp), but if you run the app on a tablet, it really doesn't look good anymore. Any chance for larger thumbnails that will scale with screen size? Thanks!

**Comment by Teifun2** [comment] 2020-11-09 18:32
I noticed this too. The problem is that the thumbnails are created by the nextcloud plugin and stored as such in the recipe folder.
There are basically two options
1. I can check if it would be possible to create larger thumbnails in the plugin and then display those. But that would require a chance of the nextcloud plugin.
2. I can load the full image and "cut" it to a thumbnail. But this would generate more traffic and take longer to load.

What do you think?

**Comment by GutHib** [comment] 2020-11-09 19:37
Appreciate the question.

Wikipedia comes to mind: Clever architecture that will resize images to any dimensions needed. One solution applied upstream saves the trouble for everyone else. So ideally, this should be fixed on the plugin level or even on the level of Nextcloud itself, because over time, more apps and plugins will run into the same problem. Why fix it dozens of times, when you can fix it once.

Then again, I guess the question is if anyone will listen, and how long they will take. If I understand you correctly, it's impossible for your app to create its own thumbnails as it's basically read-only?

Maybe offering the following options would be a decent compromise:

USE FULL IMAGE AS THUMBNAIL
- Always
- Never
- Only on Wifi Connection

Possibly in combination with strict caching, so images will only be loaded once unless the cache is reset (I mean, how often will anyone change their recipe images - VERY rarely, if ever).

**Comment by GutHib** [comment] 2020-11-15 03:16
Just as an addition, it would be great if the number of thumbnails could somehow adjust to screen width. I guess three thumbnails per row in vertical mode is fine, but if the screen is flipped horizontally, then it probably makes more sense to increase the number of thumbnails in that row rather than increase thumbnail size. (Three icons per horizontal row on a 10-inch screen looks brutal. ;) )

**Comment by Teifun2** [comment] 2020-11-21 16:42
Hmm that is a very good point. I need to check this with my tablet but i assume there should be a reasonable way to doing that. In theory i could calculate the number of categories per row with dpi? Would that make more sense?

**Comment by GutHib** [comment] 2020-11-21 23:42
Sounds perfect.

**Comment by Teifun2** [comment] 2020-12-06 13:26
I Fixed the issues with the Category Icons now. If the screen is wider more icons will be displayed.

The issue with the Thumbnails is till open though. I Did some investigation in the nextcloudCookbook.
Will need to see if i will change the nextcloud app.
https://github.com/nextcloud/cookbook/issues/406

Otherwhise this will have to wait some time until i added a Settings page. (might come with the translations)

**Comment by GutHib** [comment] 2020-12-06 14:32
Nice - thank you.

**Comment by Teifun2** [comment] 2020-12-26 11:54
As a side information:
https://github.com/nextcloud/cookbook/pull/413 Added bigger Thumbnails which i should be able to use!

There are also ongoing discussions of "more" versions of thumbnails.

**Comment by Teifun2** [comment] 2021-01-30 14:53
I could do this the same way as the app currently does. First loading the thumbnail and then in the background fetching better quality images.

**Comment by Teifun2** [comment] 2021-05-24 21:19
@GutHib Is this still an issue with the bigger thumbnails?

**Comment by GutHib** [comment] 2021-05-29 20:04
It's all good on my end, but that's basically because the number of icons per row is now relative to screen width now. On the tablet, I now get 5 vertical and 9 horizontal icons (used to be 3x3) so that fixed any problem with blurred icons as well.

**Comment by Teifun2** [comment] 2021-05-30 13:08
@GutHib Ah i see, yes that was one change that i also did. 

Well i will close this issue now. If i have added caching i might change the images to full images if they are "present" in the cache :)

**Closed by Teifun2** 2021-05-30 13:08 UTC
Labels: enhancement, need feedback
