### ISSUE TITLE
[0.3.2] Login Failure

### ISSUE THREAD

**Issue by hitam4450** [Teifun2/nextcloud-cookbook-flutter#13] opened 2020-08-19 04:10 UTC
Hi, after download and install login into **2 running nextcloud** instances was impossible !

It just does not want to connect !
regards, hitam4450

**Comment by Teifun2** [comment] 2020-08-19 05:48
Hm that's not good!
Can you tell me at what stage you got stuck?
When you entered your server url what happened next?

**Comment by hitam4450** [comment] 2020-08-19 06:11
right at the beginning..after input all credentials and press login....

**Comment by hitam4450** [comment] 2020-08-19 06:14
instead of creating an own login use perhaps existing accounts of the Nexctcloud app, like other do e.g. nextcloud notes, etc ???

**Comment by Teifun2** [comment] 2020-08-19 06:27
I have seen that nextcloud library adds support for sharing the account. Sadly this only works on android. As I want this app to also work an IOS we started with an approach that work on both systems!

In the future we could improve and add account "sharing" for the android app specifically!

What happens when you input your credentials?

**Comment by kojid0** [comment] 2020-08-19 12:18
Having problems logging in with v0.3.2 too.
After I enter the server address, log in and grant access, the nextcloud server says that the account is connected and that I can close this window now. 
But there's no way of closing this "window". Going back, closing, or force closing the app makes me have to start from the beginning again.

**Comment by Teifun2** [comment] 2020-08-19 12:49
After granting access you should be automatically redirected! If this does not happen then the app has not noticed that you gave it the correct permissions!
I will check if I can reproduce this with my nextcloud instance.

Otherwise I would probably need a test account on a instance where the login fails! You can contact me over element (riot) of the cookbook plugin if you could provide a test case.

**Comment by kojid0** [comment] 2020-08-20 09:39
I deleted all cache and data and made a clean install. Now it works. Thanks for your offered help though!

**Comment by Teifun2** [comment] 2020-08-20 16:54
@hitam4450 does clean install work for you too?

**Comment by hitam4450** [comment] 2020-08-20 18:46
Sorry, I just deleted everything ! Still use the pre 0.32 version !
i am very bus at the moment, perhaps during we i will try again !

**Comment by Teifun2** [comment] 2020-08-20 20:31
No need to hurry!

**Comment by hitam4450** [comment] 2020-09-14 07:21
The problem still exist in version 0.33 after a clean install as well !

**Comment by Teifun2** [comment] 2020-09-21 18:30
Hi, i'm sorry to hear that the issue persist.

Can you attach a screenshot of the stuck page?

**Comment by hitam4450** [comment] 2020-09-23 18:04
Nextcloud 19.0.3
ANDROID 8.0
NO Proxy.....

**Comment by Teifun2** [comment] 2020-10-14 18:57
I checked with androd 8.0 and was not able to reproduce this behaviour your seeing.

For the user in #20 i noticed it was an ssl certificate issue. If you can provide me with your nextlcoud host i could double check if it is the same problem for you. 

(In the next version i will add additional logging so that the reason for the connection issues get better)

**Comment by Teifun2** [comment] 2020-12-06 17:24
@hitam4450 
I just published a new version which should hit the google play store tomorrow? (i hope)

In this new version i changed the login flow to no longer work with this authorization page.
I now uses the username + password to create an app passsword as promoted by the nextcloud api
https://docs.nextcloud.com/server/latest/developer_manual/client_apis/LoginFlow/index.html#converting-to-app-passwords

Please let me know if this change fixed your problem!

**Comment by lmgarret** [comment] 2020-12-08 11:05
Hi ! Not OP, but latest update broke authentication for me...

Maybe you could use this https://github.com/nextcloud/Android-SingleSignOn instead of relying on username:pwd credentials ? 

Thanks for the hard work btw, really nice app :)

**Comment by ckraushaar** [comment] 2020-12-11 21:22
Having an issue with an account with two-factor authentication (TFA).  Regular accounts work.  But my account with TFA (Nextcloud TFA - not OAuth or other 3rd party) will not login.  
Using regular username and password - Invalid username and password
Using regular username and app password - 403 Error - Forbidden Access

**Comment by Teifun2** [comment] 2020-12-12 10:21
@lmgarret Hey, I'm sorry to hear that i broke login for you. Are you by any chance behind a proxy? I'm still trying to figure out a way to publish this app on IOS devices als. Therefore i cannot use android specific libraries which would break compatability.

@ckraushaar Thats a verry good point. I never looked into TFA so very likely that this will not work. I will need to do some testing to see how i can make it work. But for now i think it will not be possible. (Could also take some time to get it working :/)

**Comment by lmgarret** [comment] 2020-12-12 11:05
@Teifun2 Too bad, this login flow is pretty clean, but I get that iOS users deserve some love too :) . About the issue itself, I'm experiencing the same as @ckraushaar actually, as I'm too using 2FA on my account. Not sure if it helps, but [Nextcloud login flow doc](https://docs.nextcloud.com/server/latest/developer_manual/client_apis/LoginFlow/index.html#converting-to-app-passwords) says that 

> If the client is authenticated with an app password a 403 will be returned. If the client is authenticating with a real password an app password will be generated and returned.

Which seems to be the case here?

**Comment by Teifun2** [comment] 2020-12-12 11:58
@lmgarret it's correct that I use the flow you mentioned. The app will then create its own app password and ignore the user password.
I assume to authenticate with the TFA you would need to have an additional step? Or is it just not possible over this flow?

**Comment by lmgarret** [comment] 2020-12-12 12:30
Yes you're right, for other apps when you have 2FA enabled, you usually have to generate an application password manually in your Nextcloud user security settings. It's with this password that I get a 403 forbidden

**Comment by Teifun2** [comment] 2020-12-13 13:21
@lmgarret Ah i see! Thanks for the info. In that case i can add an alternative login flow for people who provide their own AppPassword! That should no problem at all!

**Comment by lmgarret** [comment] 2020-12-14 09:46
@Teifun2 Great, nice to hear that ! Thanks for your dedication to this app :)

**Comment by terencedesu** [comment] 2020-12-16 01:32
Excited about being able to use this app. Not sure if this fits in here or should be a new issue, but I am unable to login because my server uses a self signed certificate. Is there any workaround for this or am I not going to be able to use the app unless I use a regular certificate?

**Comment by Teifun2** [comment] 2020-12-26 11:49
@terencedesu It would probably be good if you could create a separate issue for this. As it is basically a different root cause!
I will make sure that in the next version of the app it is possible to "remove" the certificate check, so you can use self signed certificates.

Nevertheless i would highly reccomend you to use certbot for your certificates which are free and are accepted by almost all browsers as a valid certificate!

**Comment by Teifun2** [comment] 2020-12-26 23:43
@lmgarret &  @ckraushaar & @terencedesu 

I implemented two new login settings:
- Provide your own AppPassword (this should fix the 2FA problem!)
- Ignore invalid Certificate (this should enable you to use the app with self signed certificates)

I was not able to fully test the self signed fix as i didn't want to setup a new server that has wrong certificates ^^ so there might still be some issues but i actually hope i thought of everything.

I uploaded the new version as an APK here. The update on Google Play still needs to be reviewed before it will be rolled out (around 1 day). Could you check and give me feedback if this works now as soon as you have the new version?

**Comment by lmgarret** [comment] 2020-12-27 10:02
Hey @Teifun2, thanks for the quick fix! I tested the app password login this morning, which works like a charm, thanks! 👍

**Closed** 2021-01-03 15:46 UTC
Labels: bug, question

**Comment by terencedesu** [comment] 2021-02-01 23:27
@Teifun2 sorry for taking so long to reply. Thanks for this fix. Works fine and I would love to use certbot, but I am running off of a subdomain that doesn't seem to let me get a certificate.
