### ISSUE TITLE
Can't open source

### ISSUE THREAD

**Issue by blogdemoi** [Teifun2/nextcloud-cookbook-flutter#131] opened 2022-04-30 11:17 UTC
Hello,

When clicking on the source button to view the original recipe nothing happens.

I am using GraphenesOs, Android 12, your 0.7.6 version.

Thank you.

**Comment by Teifun2** [comment] 2022-05-13 19:49
Duplicate of #112

**Closed by Teifun2** 2022-05-13 19:49 UTC
