### ISSUE TITLE
Error when adding category to recipe

### ISSUE THREAD

**Issue by larrydewey** [Teifun2/nextcloud-cookbook-flutter#110] opened 2022-01-27 13:33 UTC
When adding a category to a recioe without one, the app throws a casting error:

![Screenshot_20220127-072302](https://user-images.githubusercontent.com/41640198/151368947-73f254b4-71ae-4152-8f72-e1b44464d480.png)

I don't have my comouter handy at the moment, but would be happy to provide logs if needed.

**Comment by larrydewey** [comment] 2022-02-21 23:17
This seems to also impact attempting to add or remove items from "Ingredients," etc.

**Comment by Teifun2** [comment] 2022-04-09 12:20
I have trouble to reproduce this. I am not sure if it only happens for certain recipes or with certain servers. 

Could somone attach a recipe with clear instructions how to create the error.

**Comment by patterchon** [comment] 2022-04-09 16:31
[Bulgurpfanne.zip](https://github.com/Teifun2/nextcloud-cookbook-flutter/files/8457351/Bulgurpfanne.zip)
Reproducible as follows:
1. Edit the recipe,
2. Change some words in "Zutaten" (Ingredients) list or "Zubereitung" list
3. Click "Bearbeiten" (Edit)
--> Exception occurs

**Comment by Teifun2** [comment] 2022-04-10 01:04
Hmm i tested this recipe but it seems to be working for me. So it is probably an issue related to device os or maybe to the server.

I can scan the code to try to figure out what the issue could be but this is hard for me to debug this way :/

**Comment by Kage1** [comment] 2022-04-10 12:50
It doesn't appear to be a issue with NC since I have upgraded since this was last touched. The issue still exists though. :/



 ![Screenshot_20220410-074829.jpg](https://user-images.githubusercontent.com/2062390/162618999-9cf49b0c-4d5b-424e-87d1-514c04eff5b2.jpg)

**Comment by Teifun2** [comment] 2022-04-10 14:58
Oh. I figured out why im not getting the error. It was fixed with another bug: #114

**Comment by Teifun2** [comment] 2022-04-10 15:01
It happens if the _nutrition_ field is set to empty _[]_

**Comment by Teifun2** [comment] 2022-04-10 21:25
This should be fixed with version 0.7.6

**Closed by Teifun2** 2022-04-10 21:25 UTC
Labels: bug, delivery

**Comment by Kage1** [comment] 2022-04-11 11:53
Confirmed, just updated and it's now working as expected. Thanks for the work on this.
