### ISSUE TITLE
Exception @ some recipes

### ISSUE THREAD

**Issue by tmplify** [Teifun2/nextcloud-cookbook-flutter#120] opened 2022-04-09 15:23 UTC
When I want to view an recipe I got an error:
Exception: type '_Smi' is not a subtype of type 'String' in type cast

In the nextcloud web app This error does not exist.

**Comment by Teifun2** [comment] 2022-04-09 16:32
This is a duplicate of this Issue: #114 
I just fixed it and i hope it can publish the fix soon!

**Closed by Teifun2** 2022-04-09 16:32 UTC
Labels: bug
