### ISSUE TITLE
Different language support

### ISSUE THREAD

**Issue by GutHib** [Teifun2/nextcloud-cookbook-flutter#23] opened 2020-10-10 09:36 UTC
And finally just a heads up that support for different languages isn't implemented yet. Maybe the translations for "ingredients" or "preparation time" can bet fetched automatically from the Nextcloud server?

That's it for now. Thanks for creating this app, and keep up the good work!

**Comment by Teifun2** [comment] 2020-10-14 17:35
I think this is basically a duplicate of #14 and i will close it for that reason to tidy up a little. if you disagree please come forth.

The idea to fetch translations has also been in my mind but i have not yet figured out how to do that properly :/

**Closed by Teifun2** 2020-10-14 17:35 UTC
