### ISSUE TITLE
Exception: type '_OneByteString' is not a subtype of type 'int'

### ISSUE THREAD

**Issue by meonkeys** [Teifun2/nextcloud-cookbook-flutter#181] opened 2023-03-27 23:09 UTC
Trying to view any recipe on the Android app causes this error.

    Exception: type '_OneByteString' is not a subtype of type 'int'

Workaround: use web ui.

* Cookbook app version: 0.10.2
* Nextcloud server version: 25.0.4
* Android app version: 0.7.8 (from https://f-droid.org/packages/com.nextcloud_cookbook_flutter/)

![image](https://user-images.githubusercontent.com/50639/228086914-50d4a082-957c-4759-a228-2eb3f0d0e561.jpg)

**Comment by Leptopoda** [comment] 2023-03-28 12:42
dupe of: https://github.com/Teifun2/nextcloud-cookbook-flutter/issues/178

you'll have to wait until f-droid ships the new 0.7.9 or rollback to cookbook 0.10.1

**Closed as not planned** 2023-03-28 14:14 UTC
