### ISSUE TITLE
Http Exception: Invalid status code: 405

### ISSUE THREAD

**Issue by lxto** [Teifun2/nextcloud-cookbook-flutter#157] opened 2022-09-25 07:27 UTC
Server version NC 24.05, Nextcloudpi v1.50.0
After opening the App recipes are shown with photos. When I try to open the recipe this error appeares
`Http Exception: Invalid status code: 405, uri = https://my.cloud/index.php/apps/cookbook/api/recipes/559479`

**Comment by Teifun2** [comment] 2022-09-25 08:24
Duplicate of #148 and #151

Thies should be fixes with the newest version 0.7.8.

**Closed** 2022-09-25 08:24 UTC
